FROM python:3.7-slim
LABEL Application="stylometer" maintainer="Kamil Sindi <kysindi@gmail.com>"

# System setup
ENV user app
ENV dir /home/app

RUN useradd -ms /bin/bash ${user}

WORKDIR ${dir}

RUN python3 -m ensurepip
RUN pip3 install --upgrade pip setuptools
RUN pip3 install \
  bert-serving-client \
  scikit-learn \
  numpy \
  tensorflow==2.0.0rc0 \
  tqdm

COPY train.py tfrecords.py ${dir}/
COPY model/ ${dir}/model/
COPY experiments/ ${dir}/experiments/
COPY data/ ${dir}/data/

RUN chown -R ${user}: ${dir}

# App setup
USER ${user}

CMD ["python3", "train.py"]
