FROM python:3.7-slim
LABEL Application="stylometer" maintainer="Kamil Sindi <kysindi@gmail.com>"

# System setup
ENV user app
ENV dir /home/app

RUN useradd -ms /bin/bash ${user}

WORKDIR ${dir}

RUN python3 -m ensurepip
RUN pip3 install --upgrade pip setuptools tweepy tqdm

COPY twitter_handles.txt scripts/tweet_dumper.py ${dir}/

RUN chown -R ${user}: ${dir}

# App setup
USER ${user}

CMD ["python3", "tweet_dumper.py"]
